[package]
name = "demo"
version = "0.1.0"
authors = ["Andrew Farkas <hellop@ajfarkas.dev>"]
license = "MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.86"
publish = false


[dependencies]
eframe = "0.32.1"

[dependencies.hcegui]
features = ["reorder"]
